benutzerverwaltung/benutzeraccounts/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib.auth.views import login, logout
from django.core.urlresolvers import reverse
from benutzeraccounts import views

#alle URLs die aufrubar sind, werden hier aufgelistet. Die Views-Funktionen werden angesprochen

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'benutzeraccounts/login.html'}, name='login'),
    url(r'^logout/$', logout, name='logout'),

    url(r'^profil/$', views.profile, name='profile'),
    url(r'^profil/bearbeiten/$', views.edit_profile, name='edit_profile'),

    url(r'^passwort_wechseln/$', views.change_password, name='change_password'),

    url(r'^registrieren/$', views.register, name='register'),
]

benutzerverwaltung/benutzerverwaltung/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from benutzerverwaltung import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^user/', include('benutzeraccounts.urls', namespace='user')),
    url(r'^assets/', include('benutzeraccounts.urls', namespace='assets')),
]

benutzerverwaltung/benutzeraccounts/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField
from benutzerverwaltung import settings

class Profile(models.Model):                    #Erweiterung des UserModels
    user = models.OneToOneField(User)
    salutation = models.CharField(max_length=30, default='')
    title = models.CharField(max_length=30, default='')
    phone = PhoneNumberField(default='')
    fax = PhoneNumberField(default='')
    mobile = PhoneNumberField(default='')
    birthday = models.DateField(default='')
    departement = models.CharField(max_length=50, default='')
    rank = models.CharField(max_length=80, default='')
    activity = models.CharField(max_length=50, default='')
    institute = models.CharField(max_length=50, default='')

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):       #Bei Registrierung das ProfilModel akutalisieren
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

benutzerverwaltung/benutzeraccounts/forms.py
from __future__ import unicode_literals
from django.db import models
from django import forms
from django.contrib.auth.models import User
from benutzeraccounts.models import Profile
from phonenumber_field.formfields import PhoneNumberField
from django.contrib.auth.forms import PasswordChangeForm, UserCreationForm

class UserForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=True,
    widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type': 'text',
                'name': 'first_name',
            }
        )
    )

    last_name = forms.CharField(max_length=30, required=True,
    widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type': 'text',
                'name': 'last_name',
            }
        )
    )

    email = forms.EmailField(max_length=30, required=True,
    widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type': 'hidden',
                'name': 'email',
            }
        )
    )

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email'
        )

ACTIVITY_CHOICES= [
    ('', ''),
    ('Andere', 'Andere'),
    ('Asset Management', 'Asset Management'),
    ('Business Banking', 'Business Banking'),
    ('Corporate Banking', 'Corporate Banking'),
    ('General Management', 'General Management'),
    ('Investement Banking', 'Investement Banking'),
    ('Management Services', 'Management Services'),
    ('Private Banking', 'Private Banking'),
    ('Recht/Compliance', 'Recht/Compliance'),
    ('Retail (Private und KMU)', 'Retail (Private und KMU)'),
    ('Technologie', 'Technologie'),
    ('Wealth Management', 'Wealth Management'),
    ('Ehemalige Bankiers', 'Ehemalige Bankiers'),
]

RANK_CHOICES= [
    ('', ''),
    ('Area Director', 'Area Director'),
    ('Associate Director', 'Associate Director'),
    ('CEO', 'CEO'),
    ('CEO Asset Management', 'CEO Asset Management'),
    ('CEO and President of the Manangement', 'CEO and President of the Manangement'),
    ('CEO and Chariman of the Manangement', 'CEO and Chariman of the Manangement'),
    ('CFO', 'CFO'),
    ('CFO and Member of the Executive Board', 'CFO and Member of the Executive Board'),
    ('CIO', 'CIO'),
    ('COO', 'COO'),
    ('COO and Member of the Executive Board', 'COO and Member of the Executive Board'),
    ('Chairman', 'Chairman'),
    ('Chairman of the Board', 'Chairman of the Board'),
    ('Chairman of the Board of Directors', 'Chairman of the Board of Directors'),
    ('Compliance Officer', 'Compliance Officer'),
    ('Consultant', 'Consultant'),
    ('Deputy CEO', 'Deputy CEO'),
    ('Deputy CFO', 'Deputy CFO'),
    ('Deputy General Manager', 'Deputy General Manager'),
    ('Director', 'Director'),
    ('Director and Member of the extended Management', 'Director and Member of the extended Management'),
    ('Director, Member of the Management', 'Director, Member of the Management'),
    ('Director, Chairman of the Management', 'Director, Chairman of the Management'),
    ('Ehem. Bankier', 'Ehem. Bankier'),
    ('General Manager', 'General Manager'),
    ('Group Managing Director', 'Group Managing Director'),
    ('Head Group Legal & Tax', 'Head Group Legal & Tax'),
    ('Head Human Resources', 'Head Human Resources'),
    ('Head of Asia Pasific', 'Head of Asia Pasific'),
    ('Head of Europe', 'Head of Europe'),
    ('Head of Latin America', 'Head of Latin America'),
    ('Head of Middle East', 'Head of Middle East'),
    ('Head of Compliance', 'Head of Compliance'),
    ('Head of Legal and Compliance', 'Head of Legal and Compliance'),
    ('Head of Marketing', 'Head of Marketing'),
    ('Head of Operations', 'Head of Operations'),
    ('Head of Sales', 'Head of Sales'),
    ('Honorary Chairman', 'Honorary Chairman'),
    ('Insitutional Sales Manager', 'Insitutional Sales Manager'),
    ('Legal Counsel', 'Legal Counsel'),
    ('Managing Director', 'Managing Director'),
    ('Managing Director Senior Advisor', 'Managing Director Senior Advisor'),
    ('Memeber of Divisional Executive Board', 'Memeber of Divisional Executive Board'),
    ('Member of General Management', 'Member of General Management'),
    ('Member of the Board', 'Member of the Board'),
    ('Member of the Board of Directors', 'Member of the Board of Directors'),
    ('Member of the Executive Board', 'Member of the Executive Board'),
    ('Member of the Executive Comitee', 'Member of the Executive Comitee'),
    ('Member of the Group Executive Board', 'Member of the Group Executive Board'),
    ('Member of the Group Managing Board', 'Member of the Group Managing Board'),
    ('Member of the Management Comitee', 'Member of the Management Comitee'),
    ('Member of the Operations Comitee', 'Member of the Operations Comitee'),
    ('Partner', 'Partner'),
    ('President', 'President'),
    ('Regulatory Counsel', 'Regulatory Counsel'),
    ('Relationship Manager', 'Relationship Manager'),
    ('Senior Advisor', 'Senior Advisor'),
    ('Senior Consultant', 'Senior Consultant'),
    ('Senior Manager', 'Senior Manager'),
    ('Senior Partner', 'Senior Partner'),
    ('Senior Vice President', 'Senior Vice President'),
    ('Vice CEO', 'Vice CEO'),
    ('Vice Deputy Manager', 'Vice Deputy Manager'),
    ('Vice President', 'Vice President'),
    ('Vice-Chairman', 'Vice-Chairman'),
    ('Vice-Chairman of the Board', 'Vice-Chairman of the Board'),
]

class ProfileForm(forms.ModelForm):
    salutation = forms.CharField(max_length=30, required=True,
    widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type': 'text',
                'name': 'salutation',
                'autofocus': 'autofocus'
            }
        )
    )

    title = forms.CharField(max_length=30, required=False,
    widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type': 'text',
                'name': 'title',
                'placeholder': 'Prof. Dr.'
            }
        )
    )

    phone = PhoneNumberField(required=False,
    widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type': 'tel',
                'name': 'phone',
                'placeholder': '+41581234578',
            }
        )
    )

    fax = PhoneNumberField(required=False,
    widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type': 'tel',
                'name': 'fax',
                'placeholder': '+41581234579'
            }
        )
    )

    mobile = PhoneNumberField(required=False,
    widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type': 'tel',
                'name': 'mobile',
                'placeholder': '+41761234578'
            }
        )
    )


    birthday = forms.DateField(required=False,
    widget=forms.DateInput(
            attrs={
                'class': 'form-control',
                'type': 'date',
                'name': 'birthday',
            }
        )
    )

    departement = forms.CharField(max_length=30, required=False,
    widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type': 'text',
                'name': 'departement',
                'placeholder': 'IT'
            }
        )
    )

    rank = forms.CharField(max_length=50, required=False,
    widget=forms.Select(choices=RANK_CHOICES,
            attrs={
                'class': 'form-control',
                'type': 'text',
                'name': 'rank',

            }
        )
    )

    activity = forms.CharField(max_length=50, required=False,
    widget=forms.Select(choices=ACTIVITY_CHOICES,
            attrs={
                'class': 'form-control',
                'type': 'text',
                'name': 'activity',
            }
        )
    )

    institute = forms.CharField(max_length=50, required=True,
    widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type': 'text',
                'name': 'institute',

            }
        )
    )

    class Meta:
        model = Profile
        fields = (
            'salutation',
            'title',
            'phone',
            'fax',
            'mobile',
            'birthday',
            'departement',
            'rank',
            'activity',
            'institute'
        )

    def clean_phone(self):       #Funktion zur Ueberwachung, ob Telefon und Fax unterschiedlich sind.
        phone = self.cleaned_data.get("phone")
        fax = self.cleaned_data.get("fax")
        if phone and fax and phone == fax:
            raise forms.ValidationError("") #Die Error-Message wird in den HTML-Dateien definiert
        return phone


class PasswordForm(PasswordChangeForm):
    class Meta:
        model = User
        fields = (
            'old_password',
            'new_password1',
            'new_password2',
        )

    def clean_old_password(self):       #Funktion zur Ueberwachung, ob das alte Passwort korrekt eingegeben wurde.
        old_password = self.cleaned_data.get('old_password')
        cont = User.objects.filter(old_password=old_password)
        if cont.exists():
            raise forms.ValidationError("")  #Die Error-Message wird in den HTML-Dateien definiert
        return old_password

    def clean_password(self):       #Funktion zur Ueberwachung, ob Passwoerter uebereinstimmen.
        password1 = self.cleaned_data.get("password1")

benutzerverwaltung/benutzeraccounts/views.py
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import update_session_auth_hash, authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm, UserChangeForm
from django.contrib.auth.decorators import login_required
from benutzeraccounts.models import Profile
from benutzeraccounts.forms import UserForm, ProfileForm, PasswordChangeForm, RegistrationForm
from django.db import transaction, models

def profile(request, pk=None):
    if pk:                                                                          #pk = id  pk ist unabhaengiger vom eigentlichen Primaerschluesselfeld,
        user = User.object.get(pk=pk)                                               #d. h. man muss sich nicht darum kuemmern, ob das Primaerschluesselfeld
    else:                                                                           #"id" oder "object_id" oder was auch immer heisst.
        user = request.user
    cont = {'user': user}
    return render(request, ('benutzeraccounts/profile.html'), cont)

@login_required
@transaction.atomic
def edit_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)                   #Instanz zu UserModel ueber forms
        profile_form = ProfileForm(request.POST, instance=request.user.profile)     #Instanz zu ProfileModel ueber forms
        if user_form.is_valid() and profile_form.is_valid():                        #is_valid()-Methode checkt ob Felder gueltig sind
            user_form.save()                                                        #save()-Methode speichert die eingegebenen Daten
            profile_form.save()
            return redirect(reverse('user:profile'))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    cont = {'user_form': user_form, 'profile_form':profile_form}
    return render(request, 'benutzeraccounts/edit_profile.html', cont)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)                          #Eingebaute Form wird zur Validierung angesprochen
        if form.is_valid():                                                            #Gueltigkeit der Daten pruefen
            user = form.save()
            update_session_auth_hash(request, user)                                    #Session mit neuen Daten aktualisieren
            return redirect('user:profile')                                            #Weiterleitung an Profilseite
    else:
        form = PasswordChangeForm(request.user)
    cont = {'form': form}
    return render(request, 'benutzeraccounts/change_password.html', cont)

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)                                           #Eingebaute Form wird zur Validierung angesprochen
        if form.is_valid():                                                             #Gueltigkeit der Daten pruefen
            user = form.save()                                                          #Eingaben in die Form speichern
            user.refresh_from_db()                                                      #Datenbank mit Daten akutalisieren
            user.profile.salutation = form.cleaned_data.get('salutation')               #Die Felder des ProfilModels werden einzeln geholt und gespoeichert
            user.profile.title = form.cleaned_data.get('title')
            user.profile.phone = form.cleaned_data.get('phone')
            user.profile.fax = form.cleaned_data.get('fax')
            user.profile.mobile = form.cleaned_data.get('mobile')
            user.profile.birthday = form.cleaned_data.get('birthday')
            user.profile.departement = form.cleaned_data.get('departement')
            user.profile.rank = form.cleaned_data.get('rank')
            user.profile.activity = form.cleaned_data.get('activity')
            user.profile.institute = form.cleaned_data.get('institute')
            user.save()                                                                   #Daten speichern
            password = form.cleaned_data.get('password1')                                 #password1 als Passwort des Benutzers definieren
            user = authenticate(username=user.email, password=password)                   #Ueber E-Mail und Passwort authentifizieren
            login(request, user)                                                          #Benutzer anmelden
            return redirect('user:profile')                                               #Weiterleitung an Profilseite
    else:
        form = RegistrationForm()                                                         #Bis Gueltigkeit der stimmt, Form anwenden
    cont = {'form': form}
    return render(request, 'benutzeraccounts/registration.html', cont)                    #Auf Registration-Seite bleiben

benutzerverwaltung/benutzeraccounts/templates/benutzeraccounts/change_password.html
{% extends 'basesite.html' %}

{% block head %}
  <title>Anmeldung</title>
{% endblock %}

{% block body %}
<div class="container">
  <div class="col-lg-8">
    <h1 style="margin-bottom: 0.5em">Passwort ändern</h1>
    <p style="margin-bottom: 0.5em;">
        Mit einem <b>&#10033;</b> gekennzeichnete Felder müssen ausgefüllt werden.
    </p>
    <p>
        Ihr neues Passwort:
          <li>muss mindestens acht Zeichen lang sein.
          <li>darf nicht nur aus Zahlen bestehen.
          <li>darf nicht zu ähnlich zu Ihren anderen persönlichen Informationen sein.
          <li>darf nicht allgemein üblich sein.
    </p>
      <form method="post">
        {% csrf_token %}
        <!--{{ form }}-->
        <!--der untenstehende Teil ist die designte {{ form }}-->

        <table style="margin-bottom: 1.5em; margin-top: 1.5em;" width="45%">

          <tr><td><label for="{{ form.old_password.id_for_label }}">Altes Passwort*</label></td></tr> <!--Titel für Platzhalter definieren-->
          <tr><td><input type="password" name="old_password" required autofocus id="id_old_password" class="form-control"></td></tr> <!--Platzhalter-->

          <tr><td><label style="margin-top: 1.5em;" for="{{ form.new_password1.id_for_label }}">Neues Passwort*</label></td></tr>
          <tr><td><input type="password" name="new_password1" required id="id_new_password1" class="form-control"></td></tr>

          <tr><td><label style="margin-top: 1.5em;" for="{{ form.new_password2.id_for_label }}">Neues Passwort bestätigen*</label></td></tr>
          <tr><td><input type="password" name="new_password2" required id="id_new_password2" class="form-control"></td></tr>
        </table>

        <div style="clear: both;"></div>

        <button class="btn btn-success btn-sm" type="submit">Bestätigen</button>
        <a style="margin-left: 1em;" href="{% url 'user:profile' %}" id="cancel" name="cancel" class="btn btn-default">Abbrechen</button></a>

        <div style="margin-top: 1.5em;">
          <div style="margin-bottom: 1.5em;">
            {% if form.old_password.errors %} <!--Wenn altes Passwort nicht stimmt zeige Error an-->
              <p class="label label-danger">
                Ihre altes Passwort ist nicht korrekt. Bitte versuchen Sie es erneut.
              </p>
            {% endif %}
          </div>

          <div style="margin-bottom: 1.5em;">
            {% if form.new_password2.errors %}   <!--Wenn neue Passwoerter nicht uebereinstimmen zeige Error an-->
              <p class="label label-danger">
                Ihr neues Passwort stimmt nicht überein. Bitte versuchen Sie es erneut.
              </p>
            {% endif %}
          </div>
        </div>
      </form>
  </div>
</div>
{% endblock %}

benutzerverwaltung/benutzeraccounts/templates/benutzeraccounts/login.html
{% extends 'basesite.html' %}

{% block head %}
  <title>Anmeldung</title>
{% endblock %}

{% block body %}
<div class="container">
  <div class="col-lg-5">
    <h1 style="margin-bottom: 0.5em">Anmeldung</h1>
    <p style="margin-bottom: 1.5em;">
        Geben Sie Ihren E-Mail und und Ihr Passwort ein.
    </p>
      <form method="post">
          {% csrf_token %}

          <label for="username">E-Mail</label>
          <input id="username" name="username" type="email" maxlength="50" autofocus="autofocus" required=True unique=True class="form-control">
          <label style="margin-top: 1em;" for="password">Passwort</label>
          <input style="margin-bottom: 2em;" id="password" name="password" type="password" maxlength="30" required=True class="form-control">

          <button class="btn btn-success btn-sm" type="submit" value="login">Anmelden</button><br><br>

          <!-- Error-Meldungen-->

          {% if form.errors %}
            <p class=" label label-danger">
              Ihre E-Mail-Adresse oder Passwort ist nicht korrekt. Bitte versuchen Sie es erneut.
            </p><br><br>
          {% endif %}


      </form>
  </div>
</div>
{% endblock %}

benutzerverwaltung/benutzeraccounts/templates/benutzeraccounts/profile.html
{% extends 'basesite.html' %}

{% block head %}
  <title>Profil</title>
{% endblock %}

{% block body %}
<div class="container">
  <div class="col-lg-12">
    <h1 style="margin-bottom: 0.5em">Profil von {{ user.first_name }} {{ user.last_name }}</h1>
    <p style="margin-bottom: 1.5em;">
        Stellen Sie sicher, dass Ihre Daten immer auf den neusten Stand sind.
    </p>

    <table style="float: left; margin-right: 5em;" width="30%">
        <tr><td><label>Anrede</label></td></tr>
        <tr><td><input style="margin-bottom: 1em;" class="form-control" readonly value="{{ user.profile.salutation }}"></input></td></tr>

        <tr><td><label>Titel</label></td></tr>
        <tr><td><input style="margin-bottom: 1em;" class="form-control" readonly value="{{ user.profile.title }}"></input></td></tr>

        <tr><td><label>Name</label></td></tr>
        <tr><td><input style="margin-bottom: 1em;" class="form-control" readonly value="{{ user.last_name }}"></input></td></tr>

        <tr><td><label>Vorname</label></td></tr>
        <tr><td><input style="margin-bottom: 1em;" class="form-control" readonly value="{{ user.first_name }}"></input></td></tr>

        <tr><td><label>Geburtsdatum</label></td></tr>
        <tr><td><input style="margin-bottom: 1em;" class="form-control" readonly value="{{ user.profile.birthday }}"></input></td></tr>

        <tr><td><label>Abteilung</label></td></tr>
        <tr><td><input style="margin-bottom: 1em;" class="form-control" readonly value="{{ user.profile.departement }}"></input></td></tr>

        <tr><td><label>Rang</label></td></tr>
        <tr><td><input style="margin-bottom: 1em;" class="form-control" readonly value="{{ user.profile.rank }}"></input></td></tr>
    </table>

    <table style="float: left; margin-top: 5.25em;" width="30%">
        <tr><td><label>E-Mail</label></td></tr>
        <tr><td><input style="margin-bottom: 1em;" class="form-control" readonly value="{{ user.email }}"></input></td></tr>

        <tr><td><label>Telefon</label></td></tr>
        <tr><td><input style="margin-bottom: 1em;" class="form-control" readonly value="{{ user.profile.phone }}"></input></td></tr>

        <tr><td><label>Fax</label></td></tr>
        <tr><td><input style="margin-bottom: 1em;" class="form-control" readonly value="{{ user.profile.fax }}"></input></td></tr>

        <tr><td><label>Mobil</label></td></tr>
        <tr><td><input style="margin-bottom: 1em;" class="form-control" readonly value="{{ user.profile.mobile }}"></input></td></tr>

        <tr><td><label>Tätigkeit</label></td></tr>
        <tr><td><input style="margin-bottom: 1em;" class="form-control" readonly value="{{ user.profile.activity }}"></input></td></tr>

        <tr><td><label>Institut</label></td></tr>
        <tr><td><input style="margin-bottom: 1em;" class="form-control" readonly value="{{ user.profile.institute }}"></input></td></tr>
    </table>


    <div style="clear: both;"></div>

    <div style="margin-top: 1em; margin-bottom: 5em;">
      <a href="{% url 'user:edit_profile' %}"><button class="btn btn-success btn-sm" type="submit">Profil bearbeiten</button></a>
    </div>
  </div>
</div>
{% endblock %}

benutzerverwaltung/benutzeraccounts/templates/benutzeraccounts/registration.html
{% extends 'basesite.html' %}

{% block head %}
  <title>Registrierung</title>
{% endblock %}

{% block body %}
<div class="container">
  <div class="col-lg-12">
    <h1 style="margin-bottom: 0.5em">Registrierung</h1>
    <p style="margin-bottom: 0.5em;">
        Mit einem <b>&#10033;</b> gekennzeichnete Felder müssen ausgefüllt werden.
    </p>
    <p style="margin-bottom: 1.5em;">
        Ihr Passwort:
        <li>muss mindestens acht Zeichen lang sein.
        <li>darf nicht nur aus Zahlen bestehen.
        <li>darf nicht zu ähnlich zu Ihren anderen persönlichen Informationen sein.
        <li>darf nicht allgemein üblich sein.
    </p>

    <form method="post">
      {% csrf_token %}
      <!--{{ form.as_p }}-->

      <table style="float: left; margin-top: 1em; margin-right: 5em;" width="30%">
        <tr><td><label for="{{ form.salutation.id_for_label }}">Anrede*</label></tr></td> <!--Titel für Platzhalter definieren-->
        <tr><td>{{ form.salutation }}</td></tr> <!--Platzhalter-->

        <tr><td><label style="margin-top: 1em;" for="{{ form.titel.id_for_label }}">Titel</label></tr></td>
        <tr><td>{{ form.title }}</td></tr>

        <tr><td><label style="margin-top: 1em;" for="{{ form.username.id_for_label }}">Benutzername*</label></tr></td>
        <tr><td>{{ form.username }}</td></tr>

        <tr><td><label style="margin-top: 1em;" for="{{ form.last_name.id_for_label }}">Name*</label></tr></td>
        <tr><td>{{ form.last_name }}</td></tr>

        <tr><td><label style="margin-top: 1em;" for="{{ form.first_name.id_for_label }}">Vorname*</label></tr></td>
        <tr><td>{{ form.first_name }}</td></tr>

        <tr><td><label style="margin-top: 1em;" for="{{ form.first_name.id_for_label }}">Geburtsdatum</label></tr></td>
        <tr><td>{{ form.birthday }}</tr></td>

        <tr><td><label style="margin-top: 1em;" for="{{ form.departement.id_for_label }}">Abteilung</label></tr></td>
        <tr><td>{{ form.departement }}</tr></td>

        <tr><td><label style="margin-top: 1em;" for="{{ form.rank.id_for_label }}">Rang</label></tr></td>
        <tr><td>{{ form.rank }}</tr></td>
      </table>

      <table style="float: left;" width="30%">
        <tr><td><label style="margin-top: 1em;" for="{{ form.email.id_for_label }}">E-Mail*</label></td></tr>
        <tr><td>{{ form.email }}</td></tr>

        <tr><td><label style="margin-top: 1em;" for="{{ form.phone.id_for_label }}">Telefon</label></tr></td>
        <tr><td>{{ form.phone }}</td></tr>

        <tr><td><label style="margin-top: 1em;" for="{{ form.fax.id_for_label }}">Fax</label></tr></td>
        <tr><td>{{ form.fax }}</td></tr>

        <tr><td><label style="margin-top: 1em;" for="{{ form.mobile.id_for_label }}">Mobile</label></tr></td>
        <tr><td>{{ form.mobile }}</td></tr>

        <tr><td><label style="margin-top: 1em;" for="{{ form.password1.id_for_label }}">Passwort*</label></td></tr>
        <tr><td>{{ form.password1 }}</td></tr>

        <tr><td><label style="margin-top: 1em;" for="{{ form.password2.id_for_label }}">Passwort bestätigen*</label></td></tr>
        <tr><td>{{ form.password2 }}</td></tr>

        <tr><td><label style="margin-top: 1em;" for="{{ form.activity.id_for_label }}">Tätigkeitsgebiet</label></tr></td>
        <tr><td>{{ form.activity }}</td></tr>

        <tr><td><label style="margin-top: 1em;" for="{{ form.institute.id_for_label }}">Institut*</label></tr></td>
        <tr><td>{{ form.institute }}</td></tr>

      </table>

      <div style="clear: both;"></div>

      <button style="margin-top: 1.75em; margin-bottom: 1.75em;" class="btn btn-success btn-sm" type="submit">Konto erstellen</button>
      <a style="margin-left: 1em; margin-top: 1.5em; margin-bottom: 1.5em;" href="{% url 'user:login' %}" id="cancel" name="cancel" class="btn btn-default">Abbrechen</button></a>

      <!-- Error-Meldungen-->


        <div>
          <div style="margin-bottom: 1em;">
          {% if form.username.errors %}
          <p class="label label-danger">
            Dieser Benutzername ist bereits vergeben. Bitte versuchen Sie es erneut.
          </p>
          {% endif %}
        </div>

        <div>
          {% if form.email.errors %}
          <p class="label label-danger">
            Diese E-Mail-Adresse ist bereits vergeben. Bitte versuchen Sie es erneut.
          </p>
          {% endif %}
        </div>

        <div style="margin-top: 1em; margin-bottom: 1.5em;">
          {% if form.password2.errors %}
          <p class="label label-danger">
            Ihre Passwörter stimmen nicht überein. Bitte versuchen Sie es erneut.
          </p>
          {% endif %}
        </div>

      </div>
    </form>
  </div>
</div>
{% endblock %}